Form_beginning (module8-task1 sending in module4-task1)
htmlacademy-javascript/1792885-keksobooking-24 pull request #3
Opened 2021-10-14 06:33 UTC by dimasky7

Ссылка на саму домашку ещё не работает, но ссылка на тему домашки уже работает, наверное:
https://up.htmlacademy.ru/javascript/24/module/8

Уже чешатся руки сделать вот этот пункт из тех. задания:
3.3. Поле «Тип жилья» влияет на минимальное значение поля «Цена за ночь»:
«Бунгало» — минимальная цена за ночь 0;
«Квартира» — минимальная цена за ночь 1 000;
«Отель» — минимальная цена за ночь 3 000;
«Дом» — минимальная цена 5 000;
«Дворец» — минимальная цена 10 000.

Кажется, я примерно представляю как это сделать. Нужно ещё один обработчик поставить на этот раз на selection "тип жилья", а потом добавлять аттрибут "min" в графе price. Но я решил, пока что отправить только то, что есть в домашке по 8-й теме.
Пора мне поднажать как следует, а то группа меня уже догнала, однако.

2021-10-14 08:17 UTC, 4err commented on js/form.js
> +  }
Если у нас будет больше вариантов ты заколебешься так все описывать :) Тут нужно использовать циклы. У нас известно что количество гостей всегда меньше или равно количеству комнат. Нужно в цикле перебирать все варианты, смотреть значения и те, которые не подходят выключать.

2021-10-14 10:49 UTC, 4err requested changes

2021-10-14 10:49 UTC, 4err commented on index.html
> +            <option value="0" class="guestsNumber">не для гостей</option>
Классы избыточны. Работаем с той разметкой, что есть. Ты можешь получить доступ к селекту по id и от него уже по option.

2021-10-14 10:49 UTC, 4err commented on js/form.js
> +      }
Что-то многовато циклов. Тебе нужно перебрать все пункты в рамках одного цикла и если он нам подходит, то убирать disabled, в противном случае lдобавлять.

2021-10-14 12:29 UTC, dimasky7 commented on js/form.js
> +      }
Сейчас попробую подумать как это можно сделать.

2021-10-14 13:02 UTC, dimasky7 commented on js/form.js
> +      }
Вроде сделал.

2021-10-15 06:14 UTC, 4err commented on js/form.js
> +      for (let j=0; j <=3 ; j++) {
Все еще цикл в цикле. Ты для каждого элемента еще раз проходишь по оставшимся элементам. 
Ну и именование переменных оставляет желать лучшего. Это же уже не счетчики, а какие-то данные сравниваются. А что у тебя сравнивается непонятно. Ну и магические числа какие-то. 

Алгоритм такой: ты считываешь текущее значение количества комнат и в одном цикле гостям либо задаешь либо убираешь доступность. 
Не забывай пользоваться переменной event, которая передается при событии, с помощью нее ты можешь получить много полезных данных.

2021-10-15 06:15 UTC, 4err requested changes

2021-10-15 06:15 UTC, 4err commented on js/form.js
> +    capacity.children[3].removeAttribute('disabled');
Порядок элементов может измениться. Отталкивайся от значений пунктов.

2021-10-15 09:25 UTC, dimasky7 commented on js/form.js
> +    capacity.children[3].removeAttribute('disabled');
Аааа, capacity.value, точно!

2021-10-19 10:27 UTC, merged