Module7 task1
htmlacademy-javascript/1792885-keksobooking-24 pull request #5
Opened 2021-11-05 23:46 UTC by dimasky7

2021-11-06 00:10 UTC, dimasky7 commented
Задание 11.13. "Надо подкачаться". ;) [видимо подкачка с сервера и на сервер имеется в виду]

https://up.htmlacademy.ru/javascript/24/tasks/19

Знаю, что структура далека от идеальной, но мне сейчас главное получить свои 50% выполнения задания, на остальные 50 мне абсолютно плевать, если честно {к сожалению немного лукавлю} (перфекционизм - это моя проблема, поэтому я стремлюсь к тому чтобы от него избавиться, то есть в моём случае чем хуже - тем лучше, то есть 50% - это мой идеал). Потом можно будет что-то подшлифовать, если время останется. Главное, как сказал Саша Сушко - это ТЗ.

Нужна твоя помощь в двух моментах:

1. Я не знаю как убрать чёртов балун (ты вообще раньше слышал такое слово до этих курсов?;) ) сразу после отправки формы.

2. Когда я нажимаю на кнопку "Очистить" (reset) в форме, то у меня полностью пропадает поле адреса. При этом метка на место возвращается, а поле адреса так и остается пустым, хоть моя функция и прописывает его заново - очень странно! Видимо, тут какая-то замута с CSS, которую я не могу понять. 

Что касается сброса фильтров сразу после отправки формы, то я бы очень хотел заняться этим уже в рамках следующего (последнего) задания. А то я пока что в них ничего не понимаю.

2021-11-06 17:33 UTC, 4err requested changes
Нужно вынести функции по получению и отправке данных в отдельный модуль. Нужно добавить в них коллбек и передавать функции обработчики через коллбеки.

2021-11-06 17:33 UTC, 4err commented on js/form.js
> +reset.addEventListener('click', () => {
Забыл про preventDefault оттуда и сброс происходит.

2021-11-06 17:33 UTC, 4err commented on js/fetchForForm.js
> +      document.addEventListener('keydown', (event) => {
А удалять за собой обработчики кто будет?

2021-11-07 16:15 UTC, dimasky7 commented on js/form.js
> +reset.addEventListener('click', () => {
Денис, вот вообще не понял этот момент. Я понимаю, если бы речь шла про DOM элемент формы, тогда form.preventDefault() отменяло бы всё, что написано в инпутах у формы, но при чем тут кнопка reset!? Это же всего лишь button! Тут что-что с CSS классом связано, видимо.

Я понимаю, что такое prevent default у формы - это отмена отправки формы. Но что такое prevent default у кнопки - это вообще не понятно... И как вообще CSS классы могут быть связаны с полями формы? Если reset.preventDefault() убрать, то кнопка начисто всю форму обнуляет, прямо как метод form.reset() - поразительно просто.

Я сделал, всё работает, но этот момент вообще не понятен.

2021-11-07 18:59 UTC, dimasky7 commented on js/fetchForForm.js
> +      document.addEventListener('keydown', (event) => {
Я сделал так:
document.addEventListener('click', () => {
        isError.remove();
      });
      document.removeEventListener('click', () => {
        isError.remove();
      });

Но я нифига не понимаю почему это работает... Тут написано, что только создав обработчик я тут же его удаляю, но клик то я могу сделать намного позже, а он тем не менее все равно работает, хоть обработчик уже и удален давно. Не пояснишь?

2021-11-07 19:21 UTC, dimasky7 commented
> Нужно вынести функции по получению и отправке данных в отдельный модуль. Нужно добавить в них коллбек и передавать функции обработчики через коллбеки.

Денис, вот тут хочу попросить и настоять на том, чтобы оставить этот трудный для меня момент на потом. У меня сейчас начинается рабочая неделя, соседи сверху стали жить незаконно (отдали ключи хозяевам квартиры, а сами живут там, сделав доп. ключ) и поэтому с большой вероятностью попытаются проникнуть в мою квартиру и украсть всё, что можно (т.к. знают, что у меня есть телек, Xbox и комп). Вчера они, кстати, гульбанили до 7 утра не давая мне поспать в честь своего официального отъезда (хотя на самом деле отъехали только двое из 4-х, у остальных двоих денег нет). Ну и наконец, я опаздываю. Что касается фильтрации, то там ещё и конь не валялся, а эта неделя уже последняя.

2021-11-08 06:25 UTC, 4err commented on js/form.js
> +reset.addEventListener('click', () => {
У кнопки стоит `type=reset`. CSS отвечает только за стилизацию элементов, он не умеет очищать данные. 
При нажатии на кнопку с типом reset происходит действие формы `.reset()`. И если не делать `preventDefault`, то сначала сработает твой код, а затем выполнится обычное действие кнопки, в данном случае сброс формы и он сотрет все, что ты сделал. Именно поэтому нужно сделать превент и вручную запустить сброс формы, а затем уже добавить свои вещи.

2021-11-08 06:28 UTC, 4err commented on js/fetchForForm.js
> +      document.addEventListener('keydown', (event) => {
Во-первых данный код не удаляет обработчик, поэтому все и работает :) Чтоб обработчик удалялся, нужно вынести его в функцию. 
Во-вторых его нужно удалять тогда, когда он уже не нужен: вместе с удалением заглушки об успешной отправке или ошибке.

2021-11-08 06:30 UTC, 4err commented
> > Нужно вынести функции по получению и отправке данных в отдельный модуль. Нужно добавить в них коллбек и передавать функции обработчики через коллбеки.
> 
> Денис, вот тут хочу попросить и настоять на том, чтобы оставить этот трудный для меня момент на потом. У меня сейчас начинается рабочая неделя, соседи сверху стали жить незаконно (отдали ключи хозяевам квартиры, а сами живут там, сделав доп. ключ) и поэтому с большой вероятностью попытаются проникнуть в мою квартиру и украсть всё, что можно (т.к. знают, что у меня есть телек, Xbox и комп). Вчера они, кстати, гульбанили до 7 утра не давая мне поспать в честь своего официального отъезда (хотя на самом деле отъехали только двое из 4-х, у остальных двоих денег нет). Ну и наконец, я опаздываю. Что касается фильтрации, то там ещё и конь не валялся, а эта неделя уже последняя. Мне бы хотя бы ТЗ успеть сделать бы. Но если успею, то я готов к нему вернуться. По-моему для моего 0-го уровня я итак уже весьма неплохую прогу написал. Но без фильтрации объявлений она, конечно, пока не очень. Кроме того, сейчас я могу запросто заразиться короной, т.к. работа у меня не удаленная и тогда тоже всё насмарку пойдет. Начну подыскивать себе квартиру, где так же, как и соседи можно будет подселиться незаконно (бесплатно) в этом случае, наверное. Ибо на работе меня после недавней аттестации чуть не выперли, т.к. я сейчас совсем не по специальности работаю. Так вышло, и не по моей вине.

Ты можешь оставить это на потом, однако, это часть базовых критериев, поэтому не сделав это ты не сможешь защититься. Это в любом случае нужно сделать до защиты.

2021-11-08 06:37 UTC, 4err requested changes
Обработчики все еще не удаляются корректно.

2021-11-10 05:57 UTC, merged