features nah
htmlacademy-javascript/1792885-keksobooking-24 pull request #6
Opened 2021-11-11 20:33 UTC by dimasky7

Ссылка на задание, как обычно:
https://up.htmlacademy.ru/javascript/24/module/12

В общем, без фичей вся фильтрация работает нормально. Как только подключаю к проверке условий функцию featuresMarch() всё нафиг ломается. Логика самой функции почему-то не работает, хотя на первый взгляд кажется, что всё правильно. Не могу понять в чём дело. Помоги пожалуйста разобраться, что не так у меня с этой функцией. В начале функции я прописал:
if (features) {......
.........
........
}
и return false в конце, если это условие не выполняется. Это отсеивает объявления без каких-либо фич, но и те объявления, которые с фичами фильтруются совершенно неправильно, т.к. логика работы у функции какая-то неправильная. Зачастую количество объявлений увеличивается на карте, несмотря на увеличение количества фильтров. (; 
Надеюсь на то, что проверку начнешь как можно скорее, т.к. до дедлайна времени осталось уже совсем мало.

2021-11-12 06:05 UTC, 4err requested changes

2021-11-12 06:05 UTC, 4err commented on js/main.js
> +          result = true;
Вот это присваивание `true` ломает тебе все. Допустим у меня отсутствует в объяве wifi, и у нас result будет false, однако, кондей у нас есть, а он идет дальше по списку и у тебя резалт перезапишется на true. Именно поэтому мы должны именно прерывать при нахождении отрицательного результата. А у тебя еще и остановка идет после первого успеха :)

2021-11-12 06:05 UTC, 4err commented on js/main.js
> +        if (announcement.offer.price < 10000) {
Здесь и далее куча магических чисел.

2021-11-12 06:05 UTC, 4err commented on js/main.js
> +        (price === housingPrice.value || housingPrice.value === 'any') && (featuresMatch(announcement.offer.features, filtersArray1));
Это правильно, но громоздко. Давай каждую проверку вынесем в отдельную функцию, которая будет возвращать `true/false`. Соответственно здесь останутся только вызовы этих функций, что очень сильно упростит код.

2021-11-12 20:25 UTC, dimasky7 commented
Денис, отправил тебе этот вариант, чтобы ты посмотрел правильно ли я тебя понял, на счет функции getData(onSuccess, onFail) в отдельном модуле. Удивительно, но ничего не сломалось даже. ;) С колбеками работать очень не привычно, видимо для работы с ними без адских тормозов как раз нужна практика, приличное количество практики.

Я понял, что ты хочешь, чтобы фильтрацию я тоже вынес в отдельный модуль - это я пока не сделаю, но завтра постараюсь сделать. И я так понял, ты хочешь, чтобы функцию fail я тоже вынес куда-нибудь в другой модуль. Но куда, отдельный модуль для неё что ли создать?

И последнее. Кажется я не смогу переместить getData() прямо после L.map('map-canvas')
.on('load',..............) так как для того, чтобы getData() не выдала мне ошибку нужно, чтобы const markerGroup = L.layerGroup().addTo(map); и функция const createMarker; шли до getData(); Поэтому прошу оставить её в конце, ну или главную метку я могу добавить уже после getData(), хотя по-моему это всего лишь доли микросекунд, которые будут незаметны, да и к тому же fetch - это асинхронная комманда, как я понял, а значит в любом случае начнет выполняться только после выполнения комманд синхронных. А если на счет асинхронности и синхронности я не прав, то как-то странно на мой взгляд, если метки на карте появятся ещё до того, как выполнится L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',....).addTo(map);

2021-11-16 06:09 UTC, 4err requested changes
https://take.ms/EVWey Кнопка "Очистить" в форме не сбрасывает фильтры и не возвращает карту в исходный вид.

2021-11-16 06:09 UTC, 4err commented on js/functions-for-getData.js
> +  data.slice(0, 10).forEach((announcement) => {
Что за 10? Магическое число же

2021-11-16 06:09 UTC, 4err commented on js/filter-offers.js
> +const turnOnFilters = function (data) {
Так то функция возвращает список фильтрованных объяв. Лучше что-то вроде `getFilteredData`

2021-11-16 06:09 UTC, 4err commented on js/functions-for-getData.js
> +  }, 500));
И тут магическое число

2021-11-16 06:09 UTC, 4err commented on js/functions-for-sendData.js
> +  price.setAttribute('placeholder', 1000);
Снова магия. Да и зачем? Можно в html эти параметры прописать и все будет сбрасываться как надо.

2021-11-16 06:09 UTC, 4err commented on js/offer-form.js
> +price.setAttribute('min', 1000);
Опять просто в html прописать.

2021-11-16 06:09 UTC, 4err commented on js/offer-form.js
> +  }
Не знаю как я такое пропустил. А если у тебя будет 100500 вариантов времени? Можно заменить на 
`timeOut.value = timeIn.value`. Они же у нас одинаковые всегда.

2021-11-16 06:09 UTC, 4err commented on js/offer-form.js
> +});
Тут тоже самое.

2021-11-16 13:56 UTC, dimasky7 commented on js/functions-for-sendData.js
> +  price.setAttribute('placeholder', 1000);
И будет ошибка... Вот попробуй так сделать, потом после загрузки страницы выбери Дворец, плейсхолдер измениться на 10000. Нажмешь reset, тип станет квартира, но при уменьшении цены упрешься в 10000, а не в 1000. Тоже самое будет и после отправки формы.
Кроме того, min = 0 все-таки, а не 1000. Вдруг кто html почитать захочет.

2021-11-16 13:58 UTC, dimasky7 commented
> https://take.ms/EVWey Кнопка "Очистить" в форме не сбрасывает фильтры и не возвращает карту в исходный вид.

Денис, reset работает теперь, а вот после отправки формы не работает, у меня там ошибка почему-то! Срочно нужна твоя помощь, HELP! Если раскомментишь даже хотя бы просто import одной из двух закомменченных строк, то всё сломается. Не могу понять, что за фигня!

2021-11-17 05:31 UTC, merged